
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: scs
  password:

development:
  <<: *default
  database: pmsdup_development

production:
  <<: *default
  database: pmsdup_development
